Vagrant.configure("2") do |config|

  config.vm.provider :libvirt do |domain|
    domain.memory = 2048 
    domain.cpus = 1
  end

  # Define sync folder(s)

  # Define shell provisioner
  config.vm.provision "shell", inline: <<-SHELL
    cat /tmp/hosts >> /etc/hosts
    sudo useradd -m -d /home/devops -s /bin/bash devops
    echo "devops:devops" | sudo chpasswd
    sudo useradd -m -d /home/ansible -s /bin/bash ansible
    echo "ansible:ansible" | sudo chpasswd
    sudo sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config 
    sudo systemctl restart sshd
    if [ -f /usr/bin/yum ]; then
      sudo yum clean all && rm -fr /var/cache/yum/*
    fi
    sudo cp -v /tmp/perfilado /etc/sudoers.d/
  SHELL

  config.vm.define "control" do |control|
    control.vm.box = "generic/centos7"
    control.vm.hostname = "control.lab.example.com"
    control.vm.network "private_network", ip: "10.0.0.10"
    control.vm.synced_folder "src/", "/tmp"
  end
  config.vm.define "servera" do |servera|
    servera.vm.box = "generic/centos7"
    servera.vm.hostname = "servera.lab.example.com"
    servera.vm.network "private_network", ip: "10.0.0.20"
    servera.vm.synced_folder "src/", "/tmp"
  end
  config.vm.define "serverb" do |serverb|
    serverb.vm.box = "generic/centos7"
    serverb.vm.hostname = "serverb.lab.example.com"
    serverb.vm.network "private_network", ip: "10.0.0.30"
    serverb.vm.synced_folder "src/", "/tmp"
  end
  config.vm.define "serverc" do |serverc|
    serverc.vm.box = "generic/centos7"
    serverc.vm.hostname = "serverc.lab.example.com"
    serverc.vm.network "private_network", ip: "10.0.0.40"
    serverc.vm.synced_folder "src/", "/tmp"
  end
  config.vm.define "serverd" do |serverd|
    serverd.vm.box = "generic/centos7"
    serverd.vm.hostname = "serverd.lab.example.com"
    serverd.vm.network "private_network", ip: "10.0.0.50"
    serverd.vm.synced_folder "src/", "/tmp"

    #serverd.vm.box = "generic/ubuntu1804"
    #serverd.vm.network "private_network", ip: "10.0.0.50", auto_config: false
    #serverd.vm.synced_folder "src/", "/tmp"

    #config.vm.provision "shell", inline: <<-SHELL
    # ifconfig eth1 10.0.0.50 netmask 255.255.255.0 up
    #SHELL

  end

  # Define puppet_server provisioner

end
